all:
	gcc -o main main.c adjacency_list/graph.c ../data_structures/vector/vector.c algorithms/io_file.c

adjacency_list:
	gcc -o main main.c adjacency_list/graph.c ../data_structures/vector/vector.c

adjacency_matrix:
	gcc -o main main.c adjacency_matrix/graph.c ../data_structures/vector/vector.c
